version: "2.3"

services:
    callboard:
        container_name: callboard
        image: callboard
        restart: always
        depends_on:
            - redis
            - mongo
        environment:
            PORT: 5000
            HOST: 0.0.0.0
            # DEBUG: "False"

            MONGO_HOST: mongo
            MONGO_PORT: 27017
            
            REDIS_HOST: redis
            REDIS_PORT: 6379

        build:
            context: .
        # networks:
        #     my-network:
        #         aliases:
        #             - callboard-app
        # links: 
        #     - redis
        #     - mongo


    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        # networks:
        #     default:
        #         aliases:
        #             - redis
        # networks: 
        #     - my-network
        
    
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
        # networks:
        #     default:
        #         aliases: 
        #             - db
        # networks: 
        #     - my-network

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        restart: always
        depends_on:
            - callboard
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        # networks: 
        #     - my-network
    
# networks: 
#     my-network: